### ISSUE TITLE
[Bug]: Null pointer error

### ISSUE THREAD

**Issue by yigexu** [framely/issues#1]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Use Case

1. 我修改了bot中CustomSpiceNoodle这个frame的spice slot（type从boolean改成了新增的entity），并修改了frame中对应的native function

2. 开始测试
输入 I want to order some food，first
报错
<img width="1238" alt="MaxWk2ha5a" src="https://user-images.githubusercontent.com/6505755/154913005-e50c10fb-ec1e-4149-a502-8060773c6c3e.png">

### Expected Behavior

/

### Current Behavior

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b806ff5c77cdfc256ce4/intent?page=0&imported=false&search=

**Comment by XiaoboYuan** [comment]
fixed
